NDefines.NGame.START_DATE = "1936.1.1.1"
NDefines.NGame.END_DATE = "1959.1.1.1"
NDefines.NGame.MAJOR_PARTICIPANTS_FOR_MAJOR_WAR = 10			-- Minimum number of major 

NDefines.NDiplomacy.MAX_TRUST_VALUE = 100							-- Max trust value cap.
NDefines.NDiplomacy.MIN_TRUST_VALUE = -100							-- Min trust value cap.

NDefines.NDiplomacy.MAX_OPINION_VALUE = 100						-- Max opinion value cap.
NDefines.NDiplomacy.MIN_OPINION_VALUE = -100						-- Min opinion value cap.

NDefines.NDiplomacy.BASE_PEACE_PUPPET_FACTOR = 100					-- Base factor for puppet in %.
NDefines.NDiplomacy.BASE_PEACE_LIBERATE_FACTOR = 100				-- Base factor for liberate in %.

NDefines.NDiplomacy.VERY_GOOD_OPINION = 50							-- Threshold for a country that has a very good opinion of you.
NDefines.NDiplomacy.VERY_BAD_OPINION = -50							-- Threshold for a country that has a very bad opinion of you.

NDefines.NDiplomacy.VOLUNTEERS_PER_TARGET_PROVINCE = 0.05			-- Each province owned by the target country contributes this amount of volunteers to the limit.
NDefines.NDiplomacy.VOLUNTEERS_PER_COUNTRY_ARMY = 0.05				-- Each army unit owned by the source country contributes this amount of volunteers to the limit.
NDefines.NDiplomacy.VOLUNTEERS_DIVISIONS_REQUIRED = 30				-- This many divisons are required for the country to be able to send volunteers.

NDefines.NDiplomacy.TENSION_CIVIL_WAR_IMPACT = 0.2					-- civil war multiplier on tension.
NDefines.NDiplomacy.TENSION_NO_CB_WAR = 15							-- Amount of tension generated by a no-CB wargoal
NDefines.NDiplomacy.TENSION_CB_WAR = 5								-- Amount of tension generated by a war with a CB
NDefines.NDiplomacy.TENSION_ANNEX_NO_CLAIM = 2						-- Amount of tension generated by annexing a state you don't have claims on
NDefines.NDiplomacy.TENSION_ANNEX_CLAIM = 1						-- Amount of tension generated by annexing a state you DO have claims on
NDefines.NDiplomacy.TENSION_ANNEX_CORE = 0.5						-- Amount of tension generated by annexing a state that is your core
NDefines.NDiplomacy.TENSION_PUPPET = 2								-- Amount of tension generated by puppeting (per state)
NDefines.NDiplomacy.TENSION_VOLUNTEER_FORCE_DIVISION = 0.2			-- Amount of tension generated for each sent division
NDefines.NDiplomacy.TENSION_DECAY = 0.1							-- Each months tension decays this much
NDefines.NDiplomacy.TENSION_SIZE_FACTOR = 1.0						-- All action tension values are multiplied by this value

NDefines.NDiplomacy.IDEOLOGY_JOIN_FACTION_MIN_LEVEL = 0			-- ideology limit required to join faction
NDefines.NDiplomacy.JOIN_FACTION_LIMIT_CHANGE_AT_WAR = 0			-- if in defensive war this or your modifier is counted as limit to join factions (so if you have 80% join limit this now means you can join at 50%)


NDefines.NCountry.EVENT_PROCESS_OFFSET = 20						-- Events are checked every X day per country or state (1 is ideal but CPU heavy)

NDefines.NCountry.BASE_STABILITY_WAR_FACTOR = -0.3				-- Default stability war factor
NDefines.NCountry.BASE_STABILITY_PARTY_POPULARITY_FACTOR = 0.15	-- Default stability rulling party popularity factor

NDefines.NCountry.WAR_SUPPORT_OFFNSIVE_WAR = -0.2				-- Impact of being in offensive war
NDefines.NCountry.WAR_SUPPORT_DEFENSIVE_WAR = 0.3				-- Impact of being in defensive war

NDefines.NCountry.MIN_STABILITY = 0.0
NDefines.NCountry.MAX_STABILITY = 1.0
NDefines.NCountry.MIN_WAR_SUPPORT = 0.0
NDefines.NCountry.MAX_WAR_SUPPORT = 1.0

NDefines.NCountry.FEMALE_UNIT_LEADER_BASE_CHANCE = {
	-- applies as a factor to female unit leader randomization
	-- the values needs to be zero if you don't actually have random portraits
	0.0, -- country leaders
	0.0, -- army leaders
	0.0, -- navy leaders
	0.0, -- air leaders
	1.0, -- operatives
}


NDefines.NResistance.RESISTANCE_TARGET_MODIFIER_PER_STABILITY_LOSS = 0.2	-- resistance target modifier per stability below 100%

NDefines.NResistance.GARRISON_MANPOWER_LOST_BY_ATTACK = 0.018 	-- Ratio of manpower lost by garrison at each attack on garrison (this number will be reduced by the hardness of garrison template)

NDefines.NPolitics.BASE_POLITICAL_POWER_INCREASE = 2	-- Weekly increase of PP.

NDefines.NAI.PLAN_ATTACK_MIN_ORG_FACTOR_LOW = 0.85		-- Minimum org % for a unit to actively attack an enemy unit when executing a plan
NDefines.NAI.PLAN_ATTACK_MIN_STRENGTH_FACTOR_LOW = 0.4	-- Minimum strength for a unit to actively attack an enemy unit when executing a plan
NDefines.NAI.PLAN_ATTACK_MIN_ORG_FACTOR_MED = 0.7		-- (LOWMEDHIGH) corresponds to the plan execution agressiveness level.
NDefines.NAI.PLAN_ATTACK_MIN_STRENGTH_FACTOR_MED = 0.3
NDefines.NAI.PLAN_ATTACK_MIN_ORG_FACTOR_HIGH = 0.2
NDefines.NAI.PLAN_ATTACK_MIN_STRENGTH_FACTOR_HIGH = 0.15
NDefines.NAI.PLAN_FRONTUNIT_DISTANCE_FACTOR = 10.0		-- Factor for candidate units distance to front positions.
NDefines.NAI.PLAN_ATTACK_DEPTH_FACTOR = 0.5				-- Factor applied to size or enemy being attacked.

NDefines.NAI.ORG_UNIT_STRONG = 0.75						-- Organization % for unit to be considered strong
NDefines.NAI.STR_UNIT_STRONG = 0.75						-- Strength (equipment) % for unit to be considered strong

NDefines.NAI.ORG_UNIT_WEAK = 0.15						-- Organization % for unit to be considered weak
NDefines.NAI.STR_UNIT_WEAK = 0.2						-- Strength (equipment) % for unit to be considered weak

NDefines.NAI.ORG_UNIT_NORMAL = 0.35						-- Organization % for unit to be considered normal
NDefines.NAI.STR_UNIT_NORMAL = 0.4						-- Strength (equipment) % for unit to be considered normal


NDefines.NGraphics.VICTORY_POINT_MAP_ICON_TEXT_CUTOFF = {300, 500, 750}  -- At what camera distance the VP name text disappears.
NDefines.NGraphics.VICTORY_POINTS_DISTANCE_CUTOFF = {300, 500, 1250} -- At what distance VPs are hidden
NDefines.NGraphics.MAX_NUMBER_OF_TEXTURES = 50000 -- increase if you have more than this textures

